#
# Executes commands at the start of an interactive session.

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

alias reload!='source ~/.zshrc'

# source all .zsh files inside of the zsh/ directory
for config (${ZDOTDIR:-$HOME}/.zprezto/runcoms/custom/**/*.zsh) source $config

if [[ -a ~/.localrc ]]; then
    source ~/.localrc
fi

# the nice trick with the TERM=tmux-256color-italic
# is fine for local terminals, but not for remote ones, for
# which we want the 'normal' xterm-256color 
alias ssh='TERM=xterm-256color ssh'

export PATH=$PATH:$HOME/bin

# PURE_GIT_SYMBOL="  "
# PURE_GIT_UP_ARROW="  "
# PURE_GIT_DOWN_ARROW="  "

export VISUAL=vim
export EDITOR=vim

BASE16_SHELL=$HOME/dotfiles/base16-shell/
[ -n "$PS1" ] && [ -s $BASE16_SHELL/profile_helper.sh ] && eval "$($BASE16_SHELL/profile_helper.sh)"


[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
