#
# Executes commands at the start of an interactive session.

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

alias reload!='source ~/.zshrc'

# source all .zsh files inside of the zsh/ directory
for config (${ZDOTDIR:-$HOME}/.zprezto/runcoms/custom/**/*.zsh) source $config

if [[ -a ~/.localrc ]]; then
    source ~/.localrc
fi

export VISUAL=vim
export EDITOR=vim


# added by travis gem
[ -f /Users/laurent/.travis/travis.sh ] && source /Users/laurent/.travis/travis.sh
